The-Challenger-website/config/routes.rb
Rails.application.routes.draw do

  get 'challenges/index'

  get 'challenges/create'
  post '/rate' => 'rater#create', :as => 'rate'
  post 'likes/new' => 'challenges#show'
  
  resources :likes

  resources :responses

  resources :friends

  resources :challenges do
    resources :block
  end

  resources :notifications

  resources :reports

  resources :challenges

  
  root "welcome#index"

  get 'users/welcome/index.html.erb' => 'welcome#index'
  get 'welcome/index.html.erb' => 'welcome#index'
  get 'challenges/welcome/index.html.erb' => 'welcome#index'
  get 'challenges/welcome/:id/index.html.erb' => 'welcome#index'
  get 'challenges/:id/welcome/index.html.erb' => 'welcome#index'

  resources :challenges do
    resources :comments
    
   end

  resources :challenges do
    resources :responses
  end
  
  devise_for :users, controllers: { registrations: "users/registrations" }

   resources :users

   get '/users/:controller/:action/:id/:sent_to/:status/:sent_by', to: 'users#show'

   get '/challenges/Likes', to: 'likes#index'
   get '/users/:controller/:action/:id/:blocked_by/:blocked', to: 'users#show'

   get '/notifications/:controller/:action/:notification', to: 'notifications#index'
   get '/challenges/:controller/:action/:challenge_id', to: 'responses#new'
   get '/reports/:controller/:action/:id', to: 'challenges#delete_report'
   post '/reports/:controller/:action/:id', to: 'challenges#delete_report'
 

  get 'profile/', to: 'profile#show', as: 'profile'

  
  

 

end

The-Challenger-website/app/models/user.rb
class User < ActiveRecord::Base

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthabl
  # before_save :delete_avatar, if:{ delete_avatar == '1' && !avatar_updated_at_changed? }
  
  #authored by Marina ElDib
  #It facilitates the search with the full name instead of only first name or last name
  ransacker :full_name do |parent|
    Arel::Nodes::InfixOperation.new('||',
      Arel::Nodes::InfixOperation.new('||',
        parent.table[:first_name], Arel::Nodes.build_quoted(' ')
      ),
      parent.table[:last_name]
    )
  end

   #authored by Marina ElDib
   #This method gets the user's full name to be used later in the views
   def full_name
    if self.first_name.blank? && self.last_name.blank?
        self.email
    else
        self.first_name + " " + self.last_name
    end
   end

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :challenges, :dependent => :destroy
  has_many :comments, :dependent => :destroy
  has_many :Likes, :dependent => :destroy
  has_many :reports, :dependent => :destroy
  has_many :friends, :dependent => :destroy
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "missing.jpeg"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  validates :age, :numericality => {:only_integer => true}, :allow_nil => true,
  :length => {:maximum => 2}
  # validates :age, :numericality => {:must_be_less_than_or_equal_to => 100}
  ratyrate_rater

end

The-Challenger-website/app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

The-Challenger-website/app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

The-Challenger-website/app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

The-Challenger-website/app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

 #  GET /resource/sign_up
 #  def new
 #  super
 #  end

  # POST /resource
  # def create
  #   super
  #   redirect_to @user
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

 # addeb by me 
 #  def sign_up_params
 #    allow = [:email, :password, :password_confirmation, :first_name, :last_name, :age]
 #   params.require(resource_name).permit(allow)
  #end
  protected

  # def after_sign_up_path_for(resource)
  #   '/users/#{:id}'
  # end
  
  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # You can put the params you want to permit in the empty array.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :first_name
  #   devise_parameter_sanitizer.for(:account_update) << :last_name
  #   devise_parameter_sanitizer.for(:account_update) << :age
  # end

  #These two actions set up the parameters needed for signing up and updating the profile

  def sign_up_params
    params.require(:user).permit(:first_name, :last_name, :age, :password, :password_confirmation, :avatar, :email)
  end

  def account_update_params
    params.require(:user).permit(:first_name, :last_name, :age, :password, :password_confirmation, :current_password, :avatar, :email)
  end

  #This action redirects the user to his/her profile after updating the account to see the changes

  def after_update_path_for(user)
    profile_path
  end
  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

The-Challenger-website/app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

The-Challenger-website/app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

The-Challenger-website/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :set_search

  #authored by Marina ElDib
  #It sets @search to the results of the query for the search 
  def set_search
    @search = User.search(params[:q])
  end

  #This action gets all the challenges into a variable to be used later in the view and it also
  #gets the user with the id passed and stores into the variable user
  def show
    @user = User.find(params[:id])
    @challenges = Challenge.all
  end

  #authored by Marina ElDib
  #Index returns all users or the users searched for according to their full name
  def index
     @users = User.all
    if params[:q]
     @search = User.search(params[:q])
     @users = @search.result
    end
  end

end

The-Challenger-website/app/helpers/users_helper.rb
module UsersHelper
	#Gravatar
	# def gravatar_for(user, options = {size: 50})
	# 	gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
	# 	size = options[:size]
	# 	gravatar_url = "http://gravatar.com/avatar/#{gravatar_id}?s=#{size}"
	# 	image_tag(gravatar_url, alt: user.last_name, class:"gravatar")
	# end
end

The-Challenger-website/app/views/users/index.html.erb
<% content_for :search do %>
  <div class="large-8 small-9 columns">
  <p></p>
  <%= search_form_for @search do |f| %>
  	<search>
    <%= f.text_field :full_name_cont, class:"radius-left expand", placeholder: "Challengers by Name" %>
    </search>
    <%= f.submit "Search", class:"btn btn-primary" %>
    <%= link_to "Back To Profile", current_user, class: "btn btn-warning" %>
    </div>
  <% end %>
<% end %>

<div class="container-fluid">
	<% @users.each do |user| %>
		<% if user == current_user %>
			<%= link_to "#{current_user.full_name}", '/profile/', class:"btn btn-primary" %>
		<% else %>
			<%= link_to "#{user.full_name}", user_path(user), class:"btn btn-primary" %>          
		<% end %>
	<% end %>
</div>

<style>
	th {
		text-align: center;
	}
	td {
		text-align: center;
	}
	search {
		padding-left: 10px;
	}
</style>
	

The-Challenger-website/app/views/users/show.html.erb
<!-- This part will display the user's profile picture if he/she uploaded one and otherwise it will display the defaut picture -->

<% if !flash[:notice].blank? %>
  
  <div class="alert alert-info">
  <%= flash[:notice] %>
  </div>

<% end %>

<% unless @user.avatar_file_name.blank? %>
 
  <td class="round-image-50"><%= image_tag(@user.avatar.url(:thumb)) %></td>
 
<% else %> 
 
  <td class="round-image-50"><%= image_tag(@user.avatar.url(:thumb), :size =>"100x100")%></td> 
 
<% end %> </br>

  <!-- This part will display the user's full name or email if the full name doesn't exist. It will also display a button to view all challenges. -->
 
<strong><%= @user.full_name%> </strong>
  </br>

<% unless @user.age.blank? %>

<p> Age: <%= @user.age %> </p></br>

<% end %>

<p></p>

</br>
<%= link_to "View All Challenges", challenges_path, class:"btn btn-primary" %>

<% if @user.id == current_user.id %>

  <%= link_to "New Challenge", new_challenge_path, class:"btn btn-primary" %>

  <% if @user.notifications == 0 %>
    <%= link_to "You have #{@user.notifications} new notification", notifications_path, class:"btn btn-primary" %>

  <%else%>

    <% if @user.notifications == 1 %>
      <%= link_to "You have #{@user.notifications} new notification", notifications_path, class:"btn btn-success" %>

    <%else%>
      <%= link_to "You have #{@user.notifications} new notifications", notifications_path, class:"btn btn-success" %>

    <% end %> 
  <% end %>
<%end%>

  <%= link_to "Search a Challenger", users_path, class:"btn btn-primary" %>

  <% if current_user.try(:admin?) %>
    <%= link_to "View All Reports", reports_path, class:"btn btn-danger" %>
  <%end%>

  <% @block3 = Block.find_by(:blocked_by => @user.id, :blocked => current_user.id) %>
  <% @block2 = Block.find_by(:blocked_by => current_user.id, :blocked => @user.id) %>
<% if @block3.nil? %>

  <% @friends1 = Friends.find_by(:sent_to => @user.id, :sent_by => current_user.id) %>
  <% @friends2 = Friends.find_by(:sent_to => current_user.id, :sent_by => @user.id) %>
  <% if @block2.nil? %>
    <% if current_user.id != @user.id %>
      <% session[:user_id] = @user.id %>
      <%= link_to "Block", {controller: "block", action:"create_block", blocked: @user.id, blocked_by: current_user.id}, class:"btn btn-danger" %>
      <% end %>
  <% else %>
    <%= link_to "Unblock", {controller: "block", action:"destroy", blocked: @user.id, blocked_by: current_user.id}, class:"btn btn-success" %>
  <%end%>
  <% if @friends1.nil? and @friends2.nil? %>
      <% session[:user_id] = @user.id %>
      <% if @block2.nil? %>
        <% if current_user.id != @user.id %>
          <%= link_to "Add", {controller: "friends", action:"add_friend", sent_to: @user.id, status: "Pending", sent_by: current_user.id}, class:"btn btn-success" %>
        <%end%> 
      <%end%>
  <%elsif @friends2.nil? %>
    <% if @block2.nil? %>
      <% if @friends1.status == "Accepted" %>
        <%= link_to "Unfriend", @friends1, method: :delete, class: "btn btn-danger", data: {confirm: "Are you sure that you wish to remove this friend?"} %>
      <%elsif @friends1.status == "Pending" %>
        <%= link_to "Pending Request", @friends1, method: :delete, class: "btn btn-warning", data: {confirm: "Are you sure that you wish to remove this friend?"} %>
      <% end %>  
    <% end %>  
  <%else%>
    <% if @block2.nil? %>
      <% if @friends2.status == "Accepted" %>
          <%= link_to "Unfriend", @friends2, method: :delete, class: "btn btn-danger", data: {confirm: "Are you sure that you wish to remove this friend?"} %>
      <%elsif @friends2.status == "Pending" %>
        <%= link_to "Pending Request", @friends2, method: :delete, class: "btn btn-warning", data: {confirm: "Are you sure that you wish to remove this friend?"} %>
      <%end%>
    <%end%>
  <%end%>
<% end %>

<!-- This code will load all the challenges posted by the user signed in and put them in a table. A download button, a button to view the challenge,another one to view the comments are available. A Facebook share button is also part of the code below-->

<% @block = Block.find_by(:blocked_by => @user.id, :blocked => current_user.id) %>

<%if @block.nil? %>

  <div class="container"> <h3> Challenges posted by <%= @user.full_name %> </h3></div>
  <table class="table table-bordered able-condensed table-hover">
    <thead>

      <tr>
        <th>Name</th>
        <th>Uploaded By</th>
        <th>Display Challenge</th>
        <th>Actions</th>
      </tr>

    </thead>
    <tbody>
      <% @challenges.each do |challenge| %>
       <% @challenge_owner = User.find(challenge.user1_id) %>
       <% if challenge.user1_id == @user.id %>
        <tr>
          <td ><%= challenge.name %></td>
          <td ><%= link_to "#{@challenge_owner.full_name}", user_path(challenge.user1_id)%><p></p></td>
          <% if challenge.upload_type == "Video" %>
            <td><%= video_tag challenge.path_url, :size => "320x240", :controls => true %>
            <p></p>
            <%= "#{challenge.likes_number} Liked this challenge" %></td>
          <%else%>
            <td><%= image_tag challenge.path_url, :size => "320x240" %>
            <p></p>
            <%= "#{challenge.likes_number} Liked this challenge" %></td>
          <%end%>
          <td>
          <% if challenge.user1_id != current_user.id %>
              <%= link_to "Reply", {controller: "responses", action:"new", :challenge_id => challenge.id}, class:"btn btn-success btn-block" %><p></p>
          <% end %>
          <% @test = Likes.find_by(user_id: current_user.id, path: challenge.path.to_s) %>
          <% if @test.nil? %>
            <%= link_to "👍", {controller: "likes", action:"create", file_id:challenge.id, upload_type:"Challenge" }, :method => :post, class:"btn btn-success btn-block" %>
            <p></p>
          <%else%>
            <%= link_to "👎",  @test, method: :delete, class: "btn btn-danger btn-block" %>
            <p></p>
          <%end%>
          <%= link_to "View Challenge", challenge_path(challenge), class:"btn btn-primary btn-block" %><p></p>
          <%= link_to "View Responses", {controller: "responses", action:"index", challenge_id:challenge }, class:"btn btn-primary btn-block" %><p></p>
          <p></p>
          <%= link_to "Download Challenge", challenge.path_url , class:"btn btn-primary btn-block"%><p></p>
          <% if challenge.user1_id == current_user.id or current_user.try(:admin?) %>
            <%= button_to "Delete",  challenge, method: :delete, class: "btn btn-danger btn-block", data: {confirm: "Are you sure that you wish to delete #{challenge.name}?"} %><p></p>
          <%else%>
            <%= link_to "Report", {controller: "reports", action:"new", :challenge_id => challenge.id, :user_id => challenge.user1_id}, class:"btn btn-danger btn-block" %><p></p>
          <% end %>

          <div id="fb-root"></div>
          <script>(function(d, s, id) {
          var js, fjs = d.getElementsByTagName(s)[0];
          if (d.getElementById(id)) return;
          js = d.createElement(s); js.id = id;
          js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.0";
          fjs.parentNode.insertBefore(js, fjs);
          }(document, 'script', 'facebook-jssdk'));</script>
          <div class="fb-share-button" data-href="https://developers.facebook.com/docs/plugins/" data-layout="button_count"></div>
          </td>
        </tr>
      <% end %>
      <% end %>
    </tbody>
  <% end %>
  <style>
  th {
    text-align: center;
  }
  td {
    text-align: center;
  }

</style>

The-Challenger-website/app/views/users/users.html.erb
<!-- <!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>


<h1><%= @user.email %></h1>
<ul>
    <%= content_tag(:li, ("Name: " + @user.full_name)) %>
    <%= content_tag(:li, ("Age: " + @user.age + " old")) unless @user.age.blank? %>
</ul>

</body>
</html> -->